name: docs build

on:
  push:
    branches:
      # ç¡®ä¿è¿™æ˜¯ä½ æ­£åœ¨ä½¿ç”¨çš„åˆ†æ”¯åç§°
      - main

jobs:
  vuepress-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          # è·å–æ‰€æœ‰æ ‡è®°å’Œåˆ†æ”¯çš„æ‰€æœ‰å†å²è®°å½•ï¼ˆupdatetime å¿…é¡»ï¼Œå¦åˆ™æ¯æ¬¡éƒ½ä¼šå˜åŒ–ï¼‰
          fetch-depth: 0
          # å¦‚æœä½ æ–‡æ¡£éœ€è¦ Git å­æ¨¡å—ï¼Œå–æ¶ˆæ³¨é‡Šä¸‹ä¸€è¡Œ
          # submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm add vuepress@next vuepress-theme-hope@next && pnpm remove vuepress && pnpm add vuepress-webpack@next sass-loader
          pnpm add @vuepress/plugin-google-analytics@next
          pnpm i && pnpm up
          pnpm docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # è¿™æ˜¯æ–‡æ¡£éƒ¨ç½²åˆ°çš„åˆ†æ”¯åç§°
          branch: gh-pages
          folder: docs/.vuepress/dist

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          local-dir: docs/.vuepress/dist/
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }} # å»ºè®®æ›´æ”¹é»˜è®¤çš„ 21 ç«¯å£

#      #å¤åˆ¶æ–‡ä»¶åˆ°ç›®çš„åœ°ï¼Œæ–‡æ¡£æ²¡å˜åŒ–åˆ™ä¸ä¼šå¤åˆ¶
#      - name: Copy file
#        uses: andstor/copycat-action@v3
#        with:
#          personal_token: ${{ secrets.PERSONAL_TOKEN }}
#          src_path: docs/README.md
#          dst_path: /
#          dst_owner: rockbenben
#          dst_repo_name: LearnData
#          dst_branch: main
#          src_branch: main
#          #clean: true

